### PR TITLE
fix(cluster): fix server outages due to cluster resource leakage

### LINKED ISSUE #54: Resource leak that brings down the Hub
Last night, the Hub stopped responding to all requests. Antonio Bertucci let us know about it in the Gitter chat about 5 hours ago.

When I logged into the console for the Hub and attached to the tmux session, I found the following issue:
https://github.com/nodejs/node-v0.x-archive/issues/9409

There is a work around in that thread, but I haven't had time to try it. Also we've only seen this issue once, so it may be a fluke. If it happens again, and the work around fixes it, we can be a bit more confident.

There is a [PR](https://github.com/nodejs/node-v0.x-archive/pull/9418) for the issue but it was never merged and now appears to be targetted at an abandoned repo of Node.js.

### PR DESCRIPTION
**Pull request by Splaktar**
Add initWorker() to server which should clean up worker resources on both disconnect and exit.
Reference https://github.com/nodejs/node-v0.x-archive/issues/9409
Update JSHint for server and fix some issues including removing unused requires.
Add key entries for frisbee keys.
Remove some newRelic cruft.

Fixes #54.

### CODE REVIEW

**Comment by Splaktar** [comment]
Please review the changes to `server.js` but **do not merge this** until I see if this actually fixes the issue.

This has been deployed to production, but I will need to see the server run for over 4 days straight without crashing before I can have any feeling that this might actually fix the resource leak.

**Comment by tasomaniac** [comment]
Looks good but I don't understand the part with the Frisbee client ids. They were used but not present? Could that be the reason that gcm registration was failing and we had to disable it in the app.

**Comment by Splaktar** [comment]
There was an exception thrown by the server last night due to `config.keys.frisbee` not being defined when trying to look up `config.keys.frisbee.serverClientId`. There was nothing in the code, readme, or documentation about this `config.keys.frisbee` configuration. So it's a new thing to me that was apparently undocumented and only setup on the deployment VM in OpenShift.

**Comment by Splaktar** [comment]
Still online, hoping it makes it through the weekend...

**Comment by tasomaniac** [comment]
:+1:

**Comment by Splaktar** [comment]
7 days now and the server is still up. Looks like this fix is working.

**Comment by tasomaniac** [comment]
:+1:

**Comment by tasomaniac** [comment]
:+1:

**Pull request merged**
