### PR TITLE
fix(chapter): fix broken map on chapter page

### PR DESCRIPTION
**Pull request by Splaktar**
update to use the new angular-google-maps

Includes changes from #71.

### CODE REVIEW

**Comment by tasomaniac** [comment]
This is the same work for Chapter Details page right? Changes look good to me. 

Are we now using new Google Maps SDK? I mean ours is looking really old right now.

**Comment by Splaktar** [comment]
We're using an updated version of the Angular UI angular-google-maps directive. It's getting to the point where it isn't maintained well so we might have to make a change. But this is good enough for our developers site (Hub) for now.

**Comment by Splaktar** [comment]
Before:
screen shot 2015-11-21 at 7 23 38 pm
After: 
screen shot 2015-11-21 at 7 23 49 pm

**Comment by tasomaniac** [comment]
Wow man. Thank you for fixing these.

**Comment by Splaktar** [comment]
@tasomaniac No problem. The entire site should be re-done with Angular Material at some point, but I'm just trying to get it back to working near 100% as fast as possible. Then we can focus on actual enhancements to the core functionality and APIs.

**Pull request merged**
