### PR TITLE
update(server): Remove Redis, clustering.

### LINKED ISSUE #104: Remove Redis and configure Edge caching
Redis is too much of a problem. If we can get onto GAE Flex via #100, then we can just use managed Memcache instead. But for now, we don't actually need this level of caching and should just use Google's Edge caching via headers.

Here's an example of how to setup Edge caching in Express with TypeScript

**routes/index.ts:**
```typescript
import * as express from 'express';

const MAX_AGE = 3600; // 1 hr

function addCache(request: express.Request, response: express.Response, next: express.NextFunction) {
  response.header('Cache-Control', `public, max-age=${MAX_AGE}`);
  response.header('Pragma', 'Public');
  next();
}
```

### PR DESCRIPTION
**Pull request by Splaktar**
Convert session storage to Mongo.
Enable Google Edge Caching for API.
upgrade to latest Express and related libraries
convert tasks to be triggered directly instead of via Redis+Clustering
convert cron to call new tasks
remove deprecated express-annotations
remove API docs since they depended upon express-annotations
convert rate metering to in-memory only since Redis is no longer an option
temporarily disable CSRF protection

Closes #104.

### CODE REVIEW

**Comment by Splaktar** [comment]
@VikramTiwari Would appreciate it if you could take a quick look at this please.

**Comment by VikramTiwari** [comment]
@Splaktar Thanks for the invitation to project. Edge cache config looks fine. My question is if it's wise to cache everything for 1 hour? I would normally cache images for about a day and no cacheing on API requests. I think this works and we should enhance on top of this moving forward.

**Review by VikramTiwari — APPROVED** [review]
Looks good! Gotta say good work on API. Haven't seen this project in a long time and it felt so much evolved now.

**Comment by Splaktar** [comment]
@VikramTiwari The setting in this location affects the API only. We do want to cache API requests to reduce the load on the servers and eliminate the need for running a separate Redis cluster (not cheap).

In `express.js` we're using etags and maxAge to do client side caching for 1 week via `express.static()`. I've updated the Cloud Endpoints branch to make this more clear.

**Pull request merged**
