### PR TITLE
Fix exceptions and dependency versioning

### PR DESCRIPTION
**Pull request by Splaktar**
Fix bower versions for repeatable builds.
Fix exception that start.getTime() is not a function on Moment objects.
Fix exception on undefined callback to $scope.events().
Fix exception when ingesting daily metrics if one of the results is null or undefined.

### CODE REVIEW

**Comment by tasomaniac** [comment]
Looks good. Where are exceptions stored?

**Comment by Splaktar** [comment]
Stored? They are output to the console if that's what you mean. I don't have access to the production console to see what errors the Hub is throwing atm. It might explain why updates are failing. It could also be an API key issue, but I can't know due to lack of access.

**Comment by tasomaniac** [comment]
Oh I see. Did you see these problems on your local machine?

**Comment by Splaktar** [comment]
Yes

**Comment by tasomaniac** [comment]
I first didn't want to merge the PR because I am an Android person. I think noone else is around for review, I will go ahead and merge this.

**Pull request merged**
