### PR TITLE
Fix Redis

### LINKED ISSUE #79: Redis suddenly failing Auth
Now Redis is failing for another reason. It was working just fine for a couple of days, nothing changed... and then this happened...

```
/opt/hub/node_modules/redis/index.js:575
                throw callback_err;
                      ^
Error: Ready check failed: NOAUTH Authentication required.
    at RedisClient.on_info_cmd (/opt/hub/node_modules/redis/index.js:380:35)
    at Command.callback (/opt/hub/node_modules/redis/index.js:430:14)
    at RedisClient.return_error (/opt/hub/node_modules/redis/index.js:571:25)
    at ReplyParser.<anonymous> (/opt/hub/node_modules/redis/index.js:317:18)
    at ReplyParser.emit (events.js:107:17)
    at ReplyParser.send_error (/opt/hub/node_modules/redis/lib/parser/javascript.js:296:10)
    at ReplyParser.execute (/opt/hub/node_modules/redis/lib/parser/javascript.js:181:22)
    at RedisClient.on_data (/opt/hub/node_modules/redis/index.js:547:27)
    at Socket.<anonymous> (/opt/hub/node_modules/redis/index.js:102:14)
    at Socket.emit (events.js:107:17)
```

### PR DESCRIPTION
**Pull request by Splaktar**
The JSONP issue that was affecting Firefly is fixed.
Issues where the stats or other API responses might be different within a few minutes is fixed.

Managed to upgrade Express, redis-node, connect-redis, and a few other packages without breaking anything. 

Problems seemed to be caused by our redis node 1 not being reachable via the internal network. Moving to node 3 is working for now. More attention needs to be put into making Redis and other parts of the system more HA, but that's really a full time job sort of thing...

See commit logs for more details.

This is currently deployed to production since some of these changes were required to get the Hub back online.

Fixes #79.

### CODE REVIEW

**Comment by tasomaniac** [comment]
Although code style fixes are really important, they make code review harder. I wanted to review but I was lost. :(

**Comment by tasomaniac** [comment]
I know your job here is hard and this bug has to be fixed asap. I think you can merge it.

**Comment by Splaktar** [comment]
Yeah, sorry. Realistically, I don't think any of the code changes actually fixed the primary issue which turned out to be Chinese hackers. 

So these changes are mostly just clean up and upgrading of 1+ year old / deprecated packages.

**Comment by Splaktar** [comment]
@tasomaniac Oh and the real fixes were all in the GCP Console (firewall rules and deployment of a new Redis VM). I gave you an invite with access to view the GCP project yesterday.

**Comment by tasomaniac** [comment]
Yes, I received the invite. Thank you :)

**Comment by tasomaniac** [comment]
:100:

**Pull request merged**
